---
- name: RouterOS upgrade
  hosts: routers
  gather_facts: false
  tasks:
    - name: start commands
      community.routeros.command:
        commands:
          - /system package update set channel=stable
          - /system package update check-for-updates
          - /system package update install

