- name: Remote Bash Commands
  hosts: proxmox
  gather_facts: false
  tasks:
    - name: Execute Bash command remotely
      become: yes
      shell: |
        qm list # executing bash command
      register: command_output

    - name: Print command output
      debug:
        var: command_output.stdout