- name: Remote Bash Commands
  hosts: linux_hosts

  tasks:
    - name: Execute Bash command remotely
      become: yes  # for sudo becoming
      shell: |
        shutdown now  # executing bash command
      register: command_output  # for stdout print

    - name: Print command output
      debug:
        var: command_output.stdout  # stdout