---
- name: Upload file to Windows server
  hosts: win_hosts
  tasks:
    - name: Copy file to remote Windows server
      win_copy:
        src: /ansible/servers/your_file
        dest: C:\ #Remote win path

